package me.rochblondiaux.ultralimbo.entity;

import lombok.Getter;
import net.kyori.adventure.key.Key;

@Getter
public enum EntityType {
    ACACIA_BOAT("minecraft:acacia_boat"),
    ACACIA_BOAT_CHEST("minecraft:acacia_boat_chest"),
    ALLAY("minecraft:allay"),
    AREA_EFFECT_CLOUD("minecraft:area_effect_cloud"),
    ARMADILLO("minecraft:armadillo"),
    ARMOR_STAND("minecraft:armor_stand"),
    ARROW("minecraft:arrow"),
    AXOLOTL("minecraft:axolotl"),
    BAMBOO_CHEST_RAFT("minecraft:bamboo_chest_raft"),
    BAMBOO_RAFT("minecraft:bamboo_raft"),
    BAT("minecraft:bat"),
    BEE("minecraft:bee"),
    BIRCH_BOAT("minecraft:birch_boat"),
    BIRCH_BOAT_CHEST("minecraft:birch_boat_chest"),
    BLAZE("minecraft:blaze"),
    BLOCK_DISPLAY("minecraft:block_display"),
    BOGGED("minecraft:bogged"),
    BREEZE("minecraft:breeze"),
    BREEZE_WIND_CHARGE("minecraft:breeze_wind_charge"),
    CAMEL("minecraft:camel"),
    CAT("minecraft:cat"),
    CAVE_SPIDER("minecraft:cave_spider"),
    CHERRY_BOAT("minecraft:cherry_boat"),
    CHERRY_BOAT_CHEST("minecraft:cherry_boat_chest"),
    CHEST_MINECART("minecraft:chest_minecart"),
    CHICKEN("minecraft:chicken"),
    COD("minecraft:cod"),
    COMMAND_BLOCK_MINECART("minecraft:command_block_minecart"),
    COW("minecraft:cow"),
    CREAKING("minecraft:creaking"),
    CREEPER("minecraft:creeper"),
    DARK_OAK_BOAT("minecraft:dark_oak_boat"),
    DARK_OAK_BOAT_CHEST("minecraft:dark_oak_boat_chest"),
    DOLPHIN("minecraft:dolphin"),
    DONKEY("minecraft:donkey"),
    DRAGON_FIREBALL("minecraft:dragon_fireball"),
    DROWNED("minecraft:drowned"),
    EGG("minecraft:egg"),
    ELDER_GUARDIAN("minecraft:elder_guardian"),
    ENDERMAN("minecraft:enderman"),
    ENDERMITE("minecraft:endermite"),
    ENDER_DRAGON("minecraft:ender_dragon"),
    ENDER_PEARL("minecraft:ender_pearl"),
    END_CRYSTAL("minecraft:end_crystal"),
    EVOKER("minecraft:evoker"),
    EVOKER_FANGS("minecraft:evoker_fangs"),
    EXPERIENCE_BOTTLE("minecraft:experience_bottle"),
    EXPERIENCE_ORB("minecraft:experience_orb"),
    EYE_OF_ENDER("minecraft:eye_of_ender"),
    FALLING_BLOCK("minecraft:falling_block"),
    FIREBALL("minecraft:fireball"),
    FIREWORK_ROCKET("minecraft:firework_rocket"),
    FOX("minecraft:fox"),
    FROG("minecraft:frog"),
    FURNACE_MINECART("minecraft:furnace_minecart"),
    GHAST("minecraft:ghast"),
    GIANT("minecraft:giant"),
    GLOW_ITEM_FRAME("minecraft:glow_item_frame"),
    GLOW_SQUID("minecraft:glow_squid"),
    GOAT("minecraft:goat"),
    GUARDIAN("minecraft:guardian"),
    HOGLIN("minecraft:hoglin"),
    HOPPER_MINECART("minecraft:hopper_minecart"),
    HORSE("minecraft:horse"),
    HUSK("minecraft:husk"),
    ILLUSIONER("minecraft:illusioner"),
    INTERACTION("minecraft:interaction"),
    IRON_GOLEM("minecraft:iron_golem"),
    ITEM("minecraft:item"),
    ITEM_DISPLAY("minecraft:item_display"),
    ITEM_FRAME("minecraft:item_frame"),
    JUNGLE_BOAT("minecraft:jungle_boat"),
    JUNGLE_BOAT_CHEST("minecraft:jungle_boat_chest"),
    LEASH_KNOT("minecraft:leash_knot"),
    LIGHTNING_BOLT("minecraft:lightning_bolt"),
    LLAMA("minecraft:llama"),
    LLAMA_SPIT("minecraft:llama_spit"),
    MAGMA_CUBE("minecraft:magma_cube"),
    MANGROVE_BOAT("minecraft:mangrove_boat"),
    MANGROVE_BOAT_CHEST("minecraft:mangrove_boat_chest"),
    MARKER("minecraft:marker"),
    MINECART("minecraft:minecart"),
    MOOSHROOM("minecraft:mooshroom"),
    MULE("minecraft:mule"),
    OAK_BOAT("minecraft:oak_boat"),
    OAK_BOAT_CHEST("minecraft:oak_boat_chest"),
    OCELOT("minecraft:ocelot"),
    OMINOUS_ITEM_SPAWNER("minecraft:ominous_item_spawner"),
    PAINTING("minecraft:painting"),
    PALE_OAK_BOAT("minecraft:pale_oak_boat"),
    PALE_OAK_BOAT_CHEST("minecraft:pale_oak_boat_chest"),
    PANDA("minecraft:panda"),
    PARROT("minecraft:parrot"),
    PHANTOM("minecraft:phantom"),
    PIG("minecraft:pig"),
    PIGLIN("minecraft:piglin"),
    PIGLIN_BRUTE("minecraft:piglin_brute"),
    PILLAGER("minecraft:pillager"),
    POLAR_BEAR("minecraft:polar_bear"),
    POTION("minecraft:potion"),
    PUFFERFISH("minecraft:pufferfish"),
    RABBIT("minecraft:rabbit"),
    RAVAGER("minecraft:ravager"),
    SALMON("minecraft:salmon"),
    SHEEP("minecraft:sheep"),
    SHULKER("minecraft:shulker"),
    SHULKER_BULLET("minecraft:shulker_bullet"),
    SILVERFISH("minecraft:silverfish"),
    SKELETON("minecraft:skeleton"),
    SKELETON_HORSE("minecraft:skeleton_horse"),
    SLIME("minecraft:slime"),
    SMALL_FIREBALL("minecraft:small_fireball"),
    SNIFFER("minecraft:sniffer"),
    SNOWBALL("minecraft:snowball"),
    SNOW_GOLEM("minecraft:snow_golem"),
    SPAWNER_MINECART("minecraft:spawner_minecart"),
    SPECTRAL_ARROW("minecraft:spectral_arrow"),
    SPIDER("minecraft:spider"),
    SPRUCE_BOAT("minecraft:spruce_boat"),
    SPRUCE_BOAT_CHEST("minecraft:spruce_boat_chest"),
    SQUID("minecraft:squid"),
    STRAY("minecraft:stray"),
    STRIDER("minecraft:strider"),
    TADPOLE("minecraft:tadpole"),
    TEXT_DISPLAY("minecraft:text_display"),
    TNT("minecraft:tnt"),
    TNT_MINECART("minecraft:tnt_minecart"),
    TRADER_LLAMA("minecraft:trader_llama"),
    TRIDENT("minecraft:trident"),
    TROPICAL_FISH("minecraft:tropical_fish"),
    TURTLE("minecraft:turtle"),
    VEX("minecraft:vex"),
    VILLAGER("minecraft:villager"),
    VINDICATOR("minecraft:vindicator"),
    WANDERING_TRADER("minecraft:wandering_trader"),
    WARDEN("minecraft:warden"),
    WIND_CHARGE("minecraft:wind_charge"),
    WITCH("minecraft:witch"),
    WITHER("minecraft:wither"),
    WITHER_SKELETON("minecraft:wither_skeleton"),
    WITHER_SKULL("minecraft:wither_skull"),
    WOLF("minecraft:wolf"),
    ZOGLIN("minecraft:zoglin"),
    ZOMBIE("minecraft:zombie"),
    ZOMBIE_HORSE("minecraft:zombie_horse"),
    ZOMBIE_VILLAGER("minecraft:zombie_villager"),
    ZOMBIFIED_PIGLIN("minecraft:zombified_piglin"),
    PLAYER("minecraft:player"),
    FISHING_BOBBER("minecraft:fishing_bobber");

    private final Key key;

    EntityType(String key) {
        this.key = Key.key(key);
    }

    public static EntityType fromKey(Key key) {
        for (EntityType entityType : values()) {
            if (entityType.key.equals(key)) {
                return entityType;
            }
        }
        return null;
    }
}
